[workspace]
members = [
    "crates/oafmt-cli",
    "crates/oafmt-core",
    "crates/oafmt-oas",
    "crates/oafmt-syntax",
]
exclude = ["fuzz"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/kokjinsam/oafmt"
homepage = "https://github.com/kokjinsam/oafmt"
publish = ["crates-io"]
readme = "README.md"
keywords = ["openapi", "formatter", "yaml", "json"]
categories = ["command-line-utilities", "development-tools"]

[workspace.metadata.project-tools]
cargo-deny = "0.19.7"
cargo-fuzz = "0.13.2"

[workspace.lints.rust]
unsafe_code = "forbid"
non_ascii_idents = "forbid"
warnings = "deny"
rust_2018_idioms = { level = "deny", priority = -1 }
future_incompatible = { level = "deny", priority = -1 }
nonstandard_style = { level = "deny", priority = -1 }
missing_docs = "deny"
missing_debug_implementations = "deny"
missing_copy_implementations = "deny"
unfulfilled_lint_expectations = "deny"

[workspace.lints.rustdoc]
all = { level = "deny", priority = -1 }

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
panic_in_result_fn = "deny"
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
print_stdout = "deny"
print_stderr = "deny"
await_holding_lock = "deny"
large_futures = "deny"
exit = "deny"
mem_forget = "deny"
large_stack_arrays = "deny"
large_types_passed_by_value = "deny"
multiple_crate_versions = "allow"
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
cast_precision_loss = "allow"
cast_possible_wrap = "allow"
cognitive_complexity = "allow"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
