msrv = "1.85"
cognitive-complexity-threshold = 15
type-complexity-threshold = 200
too-many-lines-threshold = 100
doc-valid-idents = [
    "..",
    "CLI",
    "CST",
    "JSON",
    "OAS",
    "OpenAPI",
    "TOML",
    "UTF-8",
    "YAML",
]
