[package]
name = "oafmt-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Pure orchestration for deterministic, syntax-preserving OpenAPI formatting"

[dependencies]
oafmt-oas = { path = "../oafmt-oas", version = "0.1.0" }
oafmt-syntax = { path = "../oafmt-syntax", version = "0.1.0" }

[lints]
workspace = true
