[package]
name = "oafmt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Command-line interface for deterministic, syntax-preserving OpenAPI formatting"

[dependencies]
ignore = "=0.4.29"
oafmt-core = { path = "../oafmt-core", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
wax = { version = "=0.7.0", default-features = false }

[[bin]]
name = "oafmt"
path = "src/main.rs"

[lints]
workspace = true
